### ISSUE TITLE
Is it possible to have a release including gapps?

### ISSUE THREAD

**Issue by robertpro** [Bliss-Bass/Bass-OS-releases#1]

**Comment by electrikjesus** [comment]
We will not be making any releases with Gapps as we are not eligible for licensing from Google. Please use the MicroG enabled builds to help further support free and open-source software. 
In the event that MicroG is not compatible with your target application, please make sure that the application is a universal or x86_64 apk. If it is not an issue with the target abi, then we always have KernelSU enabled builds that allow you to flash gapps through it. Just be aware that we will not support a build with gapps included. 

Thank you for understanding.
